# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-viralrecon-1.2.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
  - hcc
dependencies:
  ## conda-forge packages
  - conda-forge::python=3.6.11
  - conda-forge::markdown=3.3.3
  - conda-forge::pymdown-extensions=8.0.1
  - conda-forge::pygments=2.7.2
  - conda-forge::pigz=2.3.4
  - conda-forge::bc=1.07.1
  - conda-forge::r-base=4.0.3
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-tidyr=1.1.2
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-ggplot2=3.3.2
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-viridis=0.5.1

  ## bioconda packages
  ## common
  - bioconda::fastqc=0.11.9
  - bioconda::parallel-fastq-dump=0.6.6
  - bioconda::sra-tools=2.10.8
  - bioconda::fastp=0.20.1
  - bioconda::samtools=1.10
  - bioconda::bedtools=2.29.2
  - bioconda::multiqc=1.9

  ## variants
  - bioconda::bowtie2=2.4.2
  - bioconda::picard=2.23.8
  - bioconda::mosdepth=0.2.9
  - bioconda::ivar=1.3
  - bioconda::bcftools=1.10.2
  - bioconda::varscan=2.4.4
  - bioconda::ucsc-liftover=377
  - bioconda::snpeff=5.0
  - bioconda::snpsift=4.3.1t
  - bioconda::bioconductor-complexheatmap=2.6.0
  - bioconda::bioconductor-biostrings=2.58.0

  ## assembly
  - bioconda::cutadapt=3.0
  - bioconda::kraken2=2.1.1
  - bioconda::spades=3.14.1
  - bioconda::unicycler=0.4.8
  - bioconda::minia=3.2.4
  - bioconda::minimap2=2.17
  - bioconda::seqwish=0.4.1
  - bioconda::vg=1.28.0
  - bioconda::quast=5.0.2
  - bioconda::blast=2.10.1
  - bioconda::plasmidid=1.6.3
  - bioconda::bandage=0.8.1
  - bioconda::pangolin=2.1.7
  - hcc::abacas=1.3.1
